#!/bin/bash
SCRIPT=`realpath $0`
BASEDIR=$(dirname $SCRIPT)
if [ "$1" = "add" ]; then
    ${BASEDIR}/shell-butler $*
else

    result=$(${BASEDIR}/shell-butler $*)
    ret=$?

    echo -e "\U1F916 Hey"
    if [ $ret -eq 0 ]; then
        echo
        echo -e "\U1F3C3 : $result"
        echo
        eval $result
    else
        echo
        echo -e  "\U2757 You haven't selected any command"
        echo
    fi
fi
